name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Echo build job
      run: echo "Build job done"

# Unit test job
  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - uses: actions/checkout@v3
   - name: set up JDK 17
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       cache: gradle
   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
   - name: Run Linter and Test
     run: ./gradlew check
   - name: Upload Reports
     uses: actions/upload-artifact@v3.1.2
     with:
       name: Test-Reports
       path: app/build/reports
   - name: Echo test job
     run: echo "Build test done"
   
# UI test job
  run-ui-tests:
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run UI test
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with:
        api-level: 29
        script: ./gradlew connectedDebugAndroidTest
    - name: Upload Reports
      uses: actions/upload-artifact@v3.1.2
      with:
        name: UI-Test-Reports
        path: app/build/reports

# Deploy job 
  deploy:
     runs-on: ubuntu-latest
     needs: [test, run-ui-tests]
     if: github.event_name == 'pull_request'
     steps:
     - uses: actions/checkout@v3
     - name: Bump release version
       id: bump_version
       uses: christian-draeger/increment-semantic-version@1.1.0
       with:
         current-version: 'v1.0.0'
         version-fragment: 'feature'
     - name: Docker Build & Push Action
       uses: mr-smithers-excellent/docker-build-push@v6.2
       with:
          image: amitrai1603/demo-app-image
          registry: docker.io   
          tags: ${{ steps.bump_version.outputs.next-version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Echo test job
       run: echo "Build test done"
          
# Checkout main branch and build the APK
  build-main:
        runs-on: macOS-latest
        steps:
        - uses: actions/checkout@v3
          with:
              ref: main
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
              java-version: '17'
              distribution: 'temurin'
              cache: gradle
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build Master APK
          run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-master.apk
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
              name: apk_master
              path: app/build/outputs/apk/debug/app-master.apk

# Checkout PR branch and build the APK
  build-pr:
          runs-on: macOS-latest
          needs: build-main
          steps:
          - uses: actions/checkout@v3
          - name: set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
              cache: gradle
          - name: Grant execute permission for gradlew
            run: chmod +x gradlew
          - name: Build PR APK
            run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-pr.apk
          - name: Upload APK
            uses: actions/upload-artifact@v1
            with:
                name: apk_pr
                path: app/build/outputs/apk/debug/app-pr.apk

  apk-diff:
          needs: [build-main, build-pr]
          runs-on: macOS-latest
          steps:
          - uses: actions/checkout@v1
          - name: Install diffuse
            run: brew install JakeWharton/repo/diffuse
          - name: download artifact
            uses: actions/download-artifact@v2.1.1
            with:
                name: apk_master
                path: app/build/outputs/apk/debug/app-master
          - name: download artifact
            uses: actions/download-artifact@v2.1.1
            with:
                name: apk_pr
                path: app/build/outputs/apk/debug/app-pr
          - name: run differ  
            run: diffuse diff app/build/outputs/apk/debug/app-master/app-master.apk app/build/outputs/apk/debug/app-pr/app-pr.apk