name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Echo build job
      run: echo "Build job done"

# Unit test job
  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - uses: actions/checkout@v3
   - name: set up JDK 17
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       cache: gradle
   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
   - name: Run Linter and Test
     run: ./gradlew check
   - name: Upload Reports
     uses: actions/upload-artifact@v2
     with:
       name: Test-Reports
       path: app/build/reports
       if: always()
   - name: Echo test job
     run: echo "Build test done"
   
# UI test job
  run-ui-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run UI test
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with:
        api-level: 29
        script: ./gradlew connectedDebugAndroidTest
    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: UI-Test-Reports
        path: app/build/reports

# Deploy job 
  deploy:
     runs-on: ubuntu-latest
     needs: [test, run-ui-tests]
     steps:
     - uses: actions/checkout@v3
     - name: Bump release version
       id: bump_version
       uses: christian-draeger/increment-semantic-version@1.1.0
       with:
         current-version: '1.0.0'
         version-fragment: 'feature'
     - name: Do something with your bumped release version
       run: echo ${{ steps.bump_version.outputs.next-version }}
           # will print 2.12.0
     - name: Docker Build & Push Action
       uses: mr-smithers-excellent/docker-build-push@v6.2
       with:
          image: amitraikwar/demo-app-image
          registry: docker.io   
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Echo test job
       run: echo "Build test done"
          
